{% set name = "internetarchive" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/internetarchive-{{ version }}.tar.gz
  sha256: 86c011e23751f5dff1d5cc6e3bc610b2eca3331d5e502c1cd34c2021068b6bbd

build:
  entry_points:
    - ia = internetarchive.cli.ia:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - docopt >=0.6.0,<0.7.0
    - jsonpatch >=0.4
    - requests >=2.25.0,<3.0.0
    - schema >=0.4.0
    - tqdm >=4.0.0
    - urllib3 >=1.26.0

test:
  imports:
    - internetarchive
  commands:
    - pip check
    - ia --help
  requires:
    - pip

about:
  home: https://github.com/jjjake/internetarchive
  summary: A Python interface to archive.org.
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
