{% set name = "internetarchive" %}
{% set version = "5.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/internetarchive-{{ version }}.tar.gz
  sha256: b7e47f8a6739fa747c7894dd623392c2b8dd3302a9f686991c331688f065d86a

build:
  entry_points:
    - ia = internetarchive.cli.ia:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - docopt >=0.6.0,<0.7.0
    - jsonpatch >=0.4
    - requests >=2.25.0,<3.0.0
    - schema >=0.4.0
    - tqdm >=4.0.0
    - urllib3 >=1.26.0
    - importlib-metadata >=3.6.0

test:
  imports:
    - internetarchive
  commands:
    - pip check
    - ia --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jjjake/internetarchive
  summary: A Python interface to archive.org.
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
