schema_version: 1

context:
  name: internetarchive
  version: "5.8.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/internetarchive-${{ version }}.tar.gz
  sha256: 0dff14d51bafa3da587f32a8cb6478327e20c2d040a61fbfb4ad30d592062cc2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - ia = internetarchive.cli.ia:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - docopt >=0.6.0,<0.7.0
    - jsonpatch >=0.4
    - requests >=2.25.0,<3.0.0
    - schema >=0.4.0
    - tqdm >=4.0.0
    - urllib3 >=1.26.0
    - importlib-metadata >=3.6.0

tests:
  - python:
      imports:
        - internetarchive
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - ia --help

about:
  summary: A Python interface to archive.org.
  license: AGPL-3.0-or-later
  license_file: LICENSE
  homepage: https://github.com/jjjake/internetarchive

extra:
  recipe-maintainers:
    - pavelzw
